/**
 * Channels 页面静态数据
 *
 * 所有官方支持的渠道定义，按类别分组
 */
import { ReactNode } from 'react'
import {
  MessageOutlined,
  CloudOutlined,
  SlackOutlined,
  DiscordOutlined,
  GlobalOutlined,
  TeamOutlined,
  VideoCameraOutlined,
  MobileOutlined,
  ApiOutlined,
  WechatOutlined,
} from '@ant-design/icons'
import type { ChannelType, ChannelCategory } from './types'

// 所有官方支持的渠道
export const CHANNEL_TYPES: ChannelType[] = [
  // 即时通讯
  {
    id: 'telegram',
    name: 'Telegram',
    nameEn: 'Telegram',
    icon: <MessageOutlined />,
    available: true,
    category: 'im',
    description: 'Telegram 即时通讯平台',
    fields: [
      {
        key: 'botToken',
        label: 'Bot Token',
        placeholder: '1234567890:xxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
        tooltip: '通过 @BotFather 创建机器人后获得的 Token',
        type: 'password',
      },
      {
        key: 'dmPolicy',
        label: '私聊策略',
        placeholder: '',
        required: false,
        tooltip: 'pairing：需要配对授权；open：任何人可使用',
        type: 'select',
        options: [
          { label: '配对授权（推荐）', value: 'pairing' },
          { label: '开放模式', value: 'open' },
        ],
        defaultValue: 'pairing',
      },
      {
        key: 'groupPolicy',
        label: '群组策略',
        placeholder: '',
        required: false,
        tooltip: 'open：任何群组可使用；allowlist：仅白名单群组',
        type: 'select',
        options: [
          { label: '开放模式', value: 'open' },
          { label: '白名单模式', value: 'allowlist' },
        ],
        defaultValue: 'open',
      },
    ],
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    nameEn: 'WhatsApp',
    icon: <MessageOutlined />,
    available: true,
    category: 'im',
    description: 'WhatsApp 即时通讯平台（基于 Baileys）',
    fields: [
      {
        key: 'enabled',
        label: '启用',
        placeholder: '',
        required: false,
        tooltip: '启用 WhatsApp 渠道',
        type: 'switch',
        defaultValue: true,
      },
    ],
  },
  {
    id: 'signal',
    name: 'Signal',
    nameEn: 'Signal',
    icon: <MessageOutlined />,
    available: true,
    category: 'im',
    description: 'Signal 加密通讯平台',
    fields: [
      {
        key: 'enabled',
        label: '启用',
        placeholder: '',
        required: false,
        tooltip: '启用 Signal 渠道（需要 signal-cli）',
        type: 'switch',
        defaultValue: true,
      },
    ],
  },
  {
    id: 'imessage',
    name: 'iMessage',
    nameEn: 'iMessage',
    icon: <MessageOutlined />,
    available: true,
    category: 'im',
    description: 'Apple iMessage（macOS 专用）',
    fields: [],
  },
  {
    id: 'bluebubbles',
    name: 'BlueBubbles',
    nameEn: 'BlueBubbles',
    icon: <MessageOutlined />,
    available: true,
    category: 'im',
    description: 'BlueBubbles iMessage 集成（推荐）',
    fields: [
      {
        key: 'serverUrl',
        label: '服务器 URL',
        placeholder: 'https://your-server.com',
        required: true,
        tooltip: 'BlueBubbles 服务器地址',
        type: 'text',
      },
      {
        key: 'password',
        label: '服务器密码',
        placeholder: 'xxxxxxxx',
        required: true,
        tooltip: 'BlueBubbles 服务器密码',
        type: 'password',
      },
    ],
  },
  {
    id: 'line',
    name: 'LINE',
    nameEn: 'LINE',
    icon: <MessageOutlined />,
    available: true,
    category: 'im',
    description: 'LINE 即时通讯平台',
    fields: [],
  },
  {
    id: 'irc',
    name: 'IRC',
    nameEn: 'IRC',
    icon: <GlobalOutlined />,
    available: true,
    category: 'im',
    description: 'IRC 聊天协议',
    fields: [],
  },
  {
    id: 'zalo',
    name: 'Zalo',
    nameEn: 'Zalo',
    icon: <MessageOutlined />,
    available: true,
    category: 'im',
    description: 'Zalo 越南即时通讯',
    fields: [],
  },
  {
    id: 'zalouser',
    name: 'Zalo Personal',
    nameEn: 'Zalo Personal',
    icon: <MessageOutlined />,
    available: true,
    category: 'im',
    description: 'Zalo 个人版',
    fields: [],
  },
  {
    id: 'wechat',
    name: '微信',
    nameEn: 'WeChat',
    icon: <WechatOutlined />,
    available: true,
    category: 'im',
    description: '微信公众号/小程序（官方插件 @tencent-weixin/openclaw-weixin）',
    fields: [],
  },

  // 企业协作
  {
    id: 'feishu',
    name: '飞书',
    nameEn: 'Feishu',
    icon: <CloudOutlined />,
    available: true,
    category: 'enterprise',
    description: '飞书企业通讯平台',
    fields: [
      {
        key: 'appId',
        label: 'App ID',
        placeholder: 'cli_xxxxxxxxxxxxxxxx',
        required: true,
        tooltip: '飞书开放平台应用的 App ID',
        type: 'text',
      },
      {
        key: 'appSecret',
        label: 'App Secret',
        placeholder: 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
        required: true,
        tooltip: '飞书开放平台应用的 App Secret',
        type: 'password',
      },
      {
        key: 'connectionMode',
        label: '连接模式',
        placeholder: '',
        required: false,
        tooltip: 'websocket：实时推送；webhook：需配置回调地址',
        type: 'select',
        options: [
          { label: 'WebSocket（推荐）', value: 'websocket' },
          { label: 'Webhook', value: 'webhook' },
        ],
        defaultValue: 'websocket',
      },
    ],
  },
  {
    id: 'slack',
    name: 'Slack',
    nameEn: 'Slack',
    icon: <SlackOutlined />,
    available: true,
    category: 'enterprise',
    description: 'Slack 企业协作平台（基于 Bolt）',
    fields: [
      {
        key: 'botToken',
        label: 'Bot Token',
        placeholder: 'xoxb-xxxxxxxxxxxx',
        required: true,
        tooltip: 'Slack Bot Token',
        type: 'password',
      },
      {
        key: 'appToken',
        label: 'App Token',
        placeholder: 'xapp-xxxxxxxxxxxx',
        required: true,
        tooltip: 'Slack App Token（Socket Mode）',
        type: 'password',
      },
    ],
  },
  {
    id: 'discord',
    name: 'Discord',
    nameEn: 'Discord',
    icon: <DiscordOutlined />,
    available: true,
    category: 'enterprise',
    description: 'Discord 社区平台（基于 discord.js）',
    fields: [
      {
        key: 'token',
        label: 'Bot Token',
        placeholder: 'xxxxxxxxxxxxxxxxxxxx',
        required: true,
        tooltip: 'Discord Bot Token',
        type: 'password',
      },
    ],
  },
  {
    id: 'googlechat',
    name: 'Google Chat',
    nameEn: 'Google Chat',
    icon: <MessageOutlined />,
    available: true,
    category: 'enterprise',
    description: 'Google Chat 企业通讯',
    fields: [],
  },
  {
    id: 'msteams',
    name: 'Microsoft Teams',
    nameEn: 'Microsoft Teams',
    icon: <TeamOutlined />,
    available: true,
    category: 'enterprise',
    description: 'Microsoft Teams 企业协作',
    fields: [],
  },
  {
    id: 'mattermost',
    name: 'Mattermost',
    nameEn: 'Mattermost',
    icon: <GlobalOutlined />,
    available: true,
    category: 'enterprise',
    description: 'Mattermost 开源协作平台',
    fields: [],
  },
  {
    id: 'nextcloud-talk',
    name: 'Nextcloud Talk',
    nameEn: 'Nextcloud Talk',
    icon: <GlobalOutlined />,
    available: true,
    category: 'enterprise',
    description: 'Nextcloud Talk 通讯',
    fields: [],
  },
  {
    id: 'synology-chat',
    name: 'Synology Chat',
    nameEn: 'Synology Chat',
    icon: <GlobalOutlined />,
    available: true,
    category: 'enterprise',
    description: 'Synology Chat 群晖聊天',
    fields: [],
  },

  // 社交平台
  {
    id: 'twitch',
    name: 'Twitch',
    nameEn: 'Twitch',
    icon: <VideoCameraOutlined />,
    available: true,
    category: 'social',
    description: 'Twitch 直播平台',
    fields: [],
  },
  {
    id: 'nostr',
    name: 'Nostr',
    nameEn: 'Nostr',
    icon: <GlobalOutlined />,
    available: true,
    category: 'social',
    description: 'Nostr 去中心化社交协议',
    fields: [],
  },
  {
    id: 'tlon',
    name: 'Tlon',
    nameEn: 'Tlon',
    icon: <GlobalOutlined />,
    available: true,
    category: 'social',
    description: 'Tlon 去中心化通讯',
    fields: [],
  },

  // 协议/其他
  {
    id: 'matrix',
    name: 'Matrix',
    nameEn: 'Matrix',
    icon: <GlobalOutlined />,
    available: true,
    category: 'protocol',
    description: 'Matrix 去中心化通讯协议',
    fields: [],
  },
  {
    id: 'webchat',
    name: 'WebChat',
    nameEn: 'WebChat',
    icon: <GlobalOutlined />,
    available: true,
    category: 'protocol',
    description: 'Gateway 内置 WebChat（默认可用）',
    fields: [],
  },

  // 设备
  {
    id: 'macos',
    name: 'macOS',
    nameEn: 'macOS',
    icon: <MobileOutlined />,
    available: true,
    category: 'device',
    description: 'macOS 菜单栏应用',
    fields: [],
  },
  {
    id: 'ios',
    name: 'iOS',
    nameEn: 'iOS',
    icon: <MobileOutlined />,
    available: true,
    category: 'device',
    description: 'iOS 配套应用',
    fields: [],
  },
  {
    id: 'android',
    name: 'Android',
    nameEn: 'Android',
    icon: <MobileOutlined />,
    available: true,
    category: 'device',
    description: 'Android 配套应用',
    fields: [],
  },
]

// 渠道分类
export const CHANNEL_CATEGORIES: ChannelCategory[] = [
  { key: 'im', label: '即时通讯', icon: <MessageOutlined /> },
  { key: 'enterprise', label: '企业协作', icon: <TeamOutlined /> },
  { key: 'social', label: '社交平台', icon: <GlobalOutlined /> },
  { key: 'protocol', label: '协议/其他', icon: <ApiOutlined /> },
  { key: 'device', label: '设备', icon: <MobileOutlined /> },
]
